Repository oracle/macaron, pull requests merged in 2023-08, with the labels that each got.

#393 build(docker): update base image digest
  docker/Dockerfile.final
Labels: OCA Verified

#395 fix: handle cloning issues when repo is in an unexpected state
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_service/gitlab.py
Labels: OCA Verified

#396 style: enforce py311 in pyupgrade and add the adjustments
  .pre-commit-config.yaml
  src/macaron/config/defaults.py
  src/macaron/config/target_config.py
  src/macaron/database/rfc3339_datetime.py
  src/macaron/database/table_definitions.py
  src/macaron/dependency_analyzer/cyclonedx.py
  src/macaron/dependency_analyzer/java_repo_finder.py
  src/macaron/output_reporter/reporter.py
  src/macaron/output_reporter/results.py
  src/macaron/policy_engine/souffle.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/checks/base_check.py
  src/macaron/slsa_analyzer/provenance/expectations/cue/cue_validator.py
  src/macaron/slsa_analyzer/provenance/expectations/expectation.py
  src/macaron/slsa_analyzer/provenance/expectations/expectation_registry.py
Labels: OCA Verified

#397 fix(orm): use the host’s timezone when persisting datetime objects without a timezone, instead of forcing them to UTC
  src/macaron/database/rfc3339_datetime.py
Labels: OCA Verified

#406 chore(deps): update to golang.org/x/net v0.14.0
  go.mod
  go.sum
Labels: OCA Verified

#410 chore(deps): ignore GHSA-pr76-5cm5-w9cj until PyDriller updates GitPython
  Makefile
Labels: OCA Verified

#411 docs: always clean and build docs in Makefile docs target
  Makefile
Labels: OCA Verified

#419 chore(deps): use CVE-2023-40267 alias for the audit check
  Makefile
Labels: OCA Verified

#349 feat: add support for JFrog Artifactory and witness provenances produced on GitLab CI
  src/macaron/__main__.py
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/asset/__init__.py
  src/macaron/slsa_analyzer/build_tool/gradle.py
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  src/macaron/slsa_analyzer/checks/provenance_available_check.py
  src/macaron/slsa_analyzer/checks/provenance_l3_check.py
  src/macaron/slsa_analyzer/checks/provenance_l3_content_check.py
  src/macaron/slsa_analyzer/checks/provenance_witness_l1_check.py
  src/macaron/slsa_analyzer/checks/trusted_builder_l3_check.py
  src/macaron/slsa_analyzer/ci_service/base_ci_service.py
  src/macaron/slsa_analyzer/ci_service/github_actions.py
  src/macaron/slsa_analyzer/git_service/api_client.py
  src/macaron/slsa_analyzer/package_registry/__init__.py
  src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
  src/macaron/slsa_analyzer/package_registry/package_registry.py
  src/macaron/slsa_analyzer/provenance/expectations/expectation.py
  src/macaron/slsa_analyzer/provenance/intoto/__init__.py
  src/macaron/slsa_analyzer/provenance/intoto/errors.py
  src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
  src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
  src/macaron/slsa_analyzer/provenance/loader.py
  src/macaron/slsa_analyzer/provenance/provenance.py
  src/macaron/slsa_analyzer/provenance/witness/__init__.py
  src/macaron/slsa_analyzer/provenance/witness/attestor.py
  src/macaron/slsa_analyzer/specs/ci_spec.py
  src/macaron/slsa_analyzer/specs/inferred_provenance.py
  src/macaron/slsa_analyzer/specs/package_registry_spec.py
  tests/e2e/expected_results/jackson-databind/jackson-databind.json
  tests/e2e/expected_results/maven/guava.json
  tests/e2e/expected_results/maven/maven.json
  tests/e2e/expected_results/maven/mockito.json
  tests/e2e/expected_results/micronaut-core/caffeine.json
  tests/e2e/expected_results/micronaut-core/micronaut-core.json
  tests/e2e/expected_results/micronaut-core/slf4j.json
  tests/e2e/expected_results/multibuild_test/multibuild_test.json
  tests/e2e/expected_results/plot-plugin/plot-plugin.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_cue_PASS.json
  tests/e2e/expected_results/tinyMediaManager/tinyMediaManager.json
  tests/e2e/expected_results/urllib3/urllib3.json
  tests/e2e/expected_results/urllib3/urllib3_cue_invalid.json
  tests/slsa_analyzer/build_tool/test_gradle.py
  tests/slsa_analyzer/checks/test_provenance_available_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_content_check.py
  tests/slsa_analyzer/checks/test_provenance_witness_l1_check.py
  tests/slsa_analyzer/checks/test_vcs_check.py
  tests/slsa_analyzer/package_registry/__init__.py
  tests/slsa_analyzer/package_registry/test_jfrog_maven_registry.py
  tests/slsa_analyzer/provenance/intoto/__init__.py
  tests/slsa_analyzer/provenance/intoto/v01/__init__.py
  tests/slsa_analyzer/provenance/intoto/v01/test_validate.py
  tests/slsa_analyzer/provenance/test_witness_provenance.py
  tests/slsa_analyzer/test_analyze_context.py
Labels: OCA Verified, checks, package_registries

#401 feat: add purl as a CLI options
  docs/source/_static/examples/oracle-quickstart/oci-micronaut/policies/oci-micronaut-purl.dl
  docs/source/_static/examples/oracle-quickstart/oci-micronaut/policies/oci-micronaut-repo.dl
  docs/source/conf.py
  docs/source/pages/cli_usage/action_analyze.rst
  docs/source/pages/output_files.rst
  docs/source/pages/using.rst
  pyproject.toml
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  src/macaron/__main__.py
  src/macaron/config/target_config.py
  src/macaron/errors.py
  src/macaron/slsa_analyzer/analyzer.py
  tests/dependency_analyzer/expected_results/apache_maven_with_sbom_provided.json
  tests/dependency_analyzer/expected_results/cyclonedx_FasterXML_jackson-databind.json
  tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
  tests/dependency_analyzer/expected_results/cyclonedx_micronaut-projects_micronaut-core.json
  tests/dependency_analyzer/expected_results/cyclonedx_timyarkov_multibuild_test.json
  tests/dependency_analyzer/expected_results/skipdep_micronaut-projects_micronaut-core.json
  tests/dependency_analyzer/test_dependency_analyzer.py
  tests/e2e/expected_results/purl/maven/maven.json
  tests/slsa_analyzer/test_analyzer.py
Labels: OCA Verified, feature, cli, purl

#436 docs: fix a typo and missing docstrings in `jfrog_maven_registry` module
  src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
Labels: documentation, OCA Verified

#432 fix: update justifications to be complete for multi build tool projects
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  tests/e2e/expected_results/multibuild_test/multibuild_test.json
  tests/slsa_analyzer/checks/test_build_as_code_check.py
  tests/slsa_analyzer/checks/test_build_service_check.py
Labels: OCA Verified

#445 feat: support trusted SLSA L3 builders for Maven, Gradle, Node.js, and containers
  src/macaron/config/defaults.ini
Labels: OCA Verified

#444 docs: fix the instruction to run Macaron
  docs/source/pages/installation.rst
Labels: OCA Verified

#434 fix(proxy): use the host proxy settings for Maven and Gradle
  docker/user.sh
  docs/source/pages/installation.rst
  scripts/release_scripts/run_macaron.sh
Labels: bug, OCA Verified, integration

#449 chore(deps): address pip-audit reports
  Makefile
Labels: OCA Verified

#452 chore(deps): address pip-audit report for CVE-2023-41040
  Makefile
Labels: OCA Verified

#448 fix: always pull latest docker image in run_macaron.sh
  .github/workflows/_build_docker.yaml
  docs/source/pages/cli_usage/index.rst
  docs/source/pages/installation.rst
  scripts/release_scripts/run_macaron.sh
Labels: OCA Verified

#453 fix: rename `domain` to `hostname` in Git service configuration
  docs/source/pages/using.rst
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_service/base_git_service.py
  src/macaron/slsa_analyzer/git_service/github.py
  src/macaron/slsa_analyzer/git_service/gitlab.py
  src/macaron/slsa_analyzer/git_url.py
  tests/slsa_analyzer/git_service/test_gitlab.py
  tests/slsa_analyzer/test_git_url.py
Labels: OCA Verified
