Repository oracle/macaron, pull requests merged in 2023-10, with the labels that each got.

#451 feat: Go, NPM and Yarn detection
  scripts/dev_scripts/integration_tests.sh
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/build_tool/__init__.py
  src/macaron/slsa_analyzer/build_tool/go.py
  src/macaron/slsa_analyzer/build_tool/npm.py
  src/macaron/slsa_analyzer/build_tool/yarn.py
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  tests/conftest.py
  tests/e2e/expected_results/onu-ui/onu-ui.json
  tests/e2e/expected_results/react-pdf/react-pdf.json
  tests/e2e/expected_results/sget/sget.json
  tests/e2e/expected_results/uiv/uiv.json
  tests/e2e/expected_results/urllib3/urllib3.json
  tests/e2e/expected_results/yoga/yoga.json
  tests/slsa_analyzer/build_tool/__snapshots__/test_go.ambr
  tests/slsa_analyzer/build_tool/__snapshots__/test_npm.ambr
  tests/slsa_analyzer/build_tool/__snapshots__/test_yarn.ambr
  tests/slsa_analyzer/build_tool/mock_repos/go_repos/no_go_mod/dummy_file.txt
  tests/slsa_analyzer/build_tool/mock_repos/npm_repos/nested_package/project/package.json
  tests/slsa_analyzer/build_tool/mock_repos/npm_repos/no_package/dummyfile.txt
  tests/slsa_analyzer/build_tool/mock_repos/npm_repos/root_package/package.json
  tests/slsa_analyzer/build_tool/mock_repos/npm_repos/root_package_packagelock/package-lock.json
  tests/slsa_analyzer/build_tool/mock_repos/npm_repos/root_package_packagelock/package.json
  tests/slsa_analyzer/build_tool/mock_repos/yarn_repos/nested_package/project/package.json
  tests/slsa_analyzer/build_tool/mock_repos/yarn_repos/no_package/dummyfile.txt
  tests/slsa_analyzer/build_tool/mock_repos/yarn_repos/root_package/package.json
  tests/slsa_analyzer/build_tool/mock_repos/yarn_repos/root_package_packagelock/package-lock.json
  tests/slsa_analyzer/build_tool/mock_repos/yarn_repos/root_package_packagelock/package.json
  tests/slsa_analyzer/build_tool/test_go.py
  tests/slsa_analyzer/build_tool/test_npm.py
  tests/slsa_analyzer/build_tool/test_yarn.py
Labels: OCA Verified

#497 chore: do not log failed HTTP response text as error
  src/macaron/util.py
Labels: OCA Verified

#165 feat: support running the analysis with SBOM and the main software component with no repository
  docs/source/pages/cli_usage/action_verify-policy.rst
  docs/source/pages/using.rst
  scripts/dev_scripts/integration_tests.sh
  src/macaron/output_reporter/results.py
  src/macaron/output_reporter/templates/base_template.html
  src/macaron/output_reporter/templates/macaron.html
  src/macaron/slsa_analyzer/analyzer.py
  tests/dependency_analyzer/cyclonedx/resources/private_mirror_apache_maven.json
  tests/dependency_analyzer/expected_results/private_mirror_apache_maven.json
Labels: OCA Verified, SBOM

#503 chore: add changesets/action for npm release
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  tests/e2e/expected_results/sget/sget.json
Labels: OCA Verified

#504 feat: support gzipped provenance files
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/provenance/loader.py
  tests/slsa_analyzer/checks/test_provenance_l3_content_check.py
  tests/slsa_analyzer/provenance/resources/valid_provenances/slsa-verifier-linux-amd64.intoto.jsonl.gz
Labels: OCA Verified

#509 chore: fix type correctness and remove many "type: ignore" directives
  src/macaron/__main__.py
  src/macaron/database/table_definitions.py
  src/macaron/database/views.py
  src/macaron/dependency_analyzer/dependency_resolver.py
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/checks/check_result.py
  src/macaron/slsa_analyzer/checks/provenance_l3_content_check.py
  src/macaron/slsa_analyzer/git_service/api_client.py
  src/macaron/slsa_analyzer/provenance/expectations/expectation.py
  src/macaron/slsa_analyzer/slsa_req.py
  src/macaron/util.py
  tests/slsa_analyzer/checks/test_registry.py
Labels: OCA Verified

#520 chore: avoid running python dev scripts with system python
  scripts/dev_scripts/integration_tests_docker.sh
  scripts/dev_scripts/test_run_macaron_sh.py
  tests/dependency_analyzer/compare_dependencies.py
  tests/e2e/compare_e2e_result.py
  tests/e2e/repo_finder/repo_finder.py
  tests/policy_engine/compare_policy_reports.py
Labels: OCA Verified

#525 docs: add entries for npm, Yarn, and Go build tools
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.build_tool.rst
Labels: OCA Verified

#521 chore: improve the run_macaron.sh script
  docs/source/pages/cli_usage/command_analyze.rst
  docs/source/pages/cli_usage/command_dump_defaults.rst
  docs/source/pages/cli_usage/command_verify-policy.rst
  docs/source/pages/cli_usage/index.rst
  docs/source/pages/output_files.rst
  docs/source/pages/tutorials/index.rst
  docs/source/pages/using.rst
  scripts/dev_scripts/test_run_macaron_sh.py
  scripts/release_scripts/run_macaron.sh
Labels: OCA Verified

#511 chore: do not pass *args to SQLALchemy DeclarativeBase class
  src/macaron/database/table_definitions.py
Labels: OCA Verified

#528 fix: fix bash syntax error when running `run_macaron.sh` on MacOS
  docs/source/pages/installation.rst
  scripts/release_scripts/run_macaron.sh
Labels: OCA Verified

#483 feat: add download timeout config
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/git_service/api_client.py
Labels: OCA Verified

#491 fix: do not use git set-branches if the target branch is not currently available in the repository
  src/macaron/slsa_analyzer/git_url.py
Labels: OCA Verified

#531 chore: print debug message if a ci service config file is not found
  src/macaron/slsa_analyzer/ci_service/base_ci_service.py
Labels: OCA Verified

#533 chore: improve the log message in repo finder
  src/macaron/repo_finder/repo_finder.py
Labels: OCA Verified, repository_finder

#532 refactor!: allow the branch name in the schema of a repository to be null
  docs/source/assets/er-diagram.svg
  src/macaron/database/table_definitions.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/ci_service/base_ci_service.py
  src/macaron/slsa_analyzer/ci_service/circleci.py
  src/macaron/slsa_analyzer/ci_service/github_actions.py
  src/macaron/slsa_analyzer/ci_service/gitlab_ci.py
  src/macaron/slsa_analyzer/ci_service/jenkins.py
  src/macaron/slsa_analyzer/ci_service/travis.py
  src/macaron/slsa_analyzer/git_service/api_client.py
  tests/conftest.py
  tests/slsa_analyzer/checks/test_build_service_check.py
  tests/slsa_analyzer/checks/test_provenance_available_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_content_check.py
  tests/slsa_analyzer/checks/test_trusted_builder_l3_check.py
Labels: OCA Verified, repository_finder, database
