Repository oracle/macaron, pull requests merged in 2023-07, with the labels that each got.

#350 docs: add instructions on using repo finder
  docs/source/pages/cli_usage/action_dump_defaults.rst
  docs/source/pages/using.rst
Labels: OCA Verified

#352 chore: remove logging in clone_remote_repo function
  scripts/release_scripts/run_macaron.sh
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_service/__init__.py
  src/macaron/slsa_analyzer/git_service/gitlab.py
  src/macaron/slsa_analyzer/git_url.py
  tests/slsa_analyzer/git_service/test_gitlab.py
  tests/slsa_analyzer/test_git_url.py
Labels: OCA Verified

#271 feat: resolve Maven properties in found POMs
  src/macaron/dependency_analyzer/java_repo_finder.py
  tests/dependency_analyzer/java_repo_finder/resources/example_pom.xml
  tests/dependency_analyzer/java_repo_finder/test_java_repo_finder.py
Labels: OCA Verified

#354 chore: update gitlab repo remote url
  src/macaron/errors.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_service/base_git_service.py
  src/macaron/slsa_analyzer/git_service/bitbucket.py
  src/macaron/slsa_analyzer/git_service/github.py
  src/macaron/slsa_analyzer/git_service/gitlab.py
  tests/slsa_analyzer/git_service/resources/self_hosted_gitlab_repo/test.txt
  tests/slsa_analyzer/git_service/test_gitlab.py
Labels: OCA Verified

#359 test: fail on unraisable exceptions
  pyproject.toml
Labels: OCA Verified

#362 chore: fix black and flake8 issues for the new versions of the tools
  docs/source/conf.py
  src/macaron/parsers/bashparser.py
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/provenance_l3_check.py
  src/macaron/slsa_analyzer/database_store.py
  tests/slsa_analyzer/checks/base_check/test_base_check.py
Labels: OCA Verified

#366 fix: check paths in an archive file before extracting
  src/macaron/slsa_analyzer/checks/provenance_l3_check.py
  src/macaron/util.py
Labels: OCA Verified

#360 chore(deps-dev): update pre-commit and the hooks
  .pre-commit-config.yaml
  pyproject.toml
Labels: OCA Verified

#361 docs: add instructions for analyzing GitLab repositories
  docs/source/pages/using.rst
  src/macaron/config/defaults.ini
Labels: documentation, OCA Verified, git_service

#370 build(docs): adjust the Makefile docs target
  Makefile
Labels: OCA Verified

#377 docs: remove manual modifications to generated rst files
  docs/source/conf.py
  docs/source/pages/apidoc/macaron.code_analyzer.rst
  docs/source/pages/apidoc/macaron.config.rst
  docs/source/pages/apidoc/macaron.database.rst
  docs/source/pages/apidoc/macaron.dependency_analyzer.rst
  docs/source/pages/apidoc/macaron.output_reporter.rst
  docs/source/pages/apidoc/macaron.parsers.rst
  docs/source/pages/apidoc/macaron.parsers.yaml.rst
  docs/source/pages/apidoc/macaron.policy_engine.rst
  docs/source/pages/apidoc/macaron.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.build_tool.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.checks.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.ci_service.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.git_service.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.expectations.cue.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.expectations.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.specs.rst
  src/macaron/database/table_definitions.py
  src/macaron/slsa_analyzer/provenance/expectations/__init__.py
  src/macaron/slsa_analyzer/provenance/expectations/cue/__init__.py
Labels: documentation, OCA Verified

#379 chore: upgrade to python 3.11.4
  docker/Dockerfile.base
  docker/Dockerfile.final
Labels: OCA Verified

#384 ci: make line-length checks a bit more tolerant using Bugbear only
  .flake8
  pyproject.toml
Labels: OCA Verified

#381 fix(orm): serialize datetime object’s timezone instead of always coercing to UTC when persisting to the SQLite db
  src/macaron/database/rfc3339_datetime.py
Labels: OCA Verified

#383 build: improve Makefile setup on macOS
  Makefile
  src/macaron/config/defaults.py
Labels: OCA Verified

#386 docs: update Go version to 1.20 in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: OCA Verified

#387 build: do not update Go dependencies in Makefile setup
  Makefile
Labels: OCA Verified
