Repository oracle/macaron, pull requests merged in 2023-05, with the labels that each got.

#208 test: return error when defaults.ini provided by user does not exist
  src/macaron/__main__.py
  src/macaron/config/defaults.py
  tests/config/resources/defaults.ini
  tests/config/test_defaults.py
Labels: OCA Verified

#210 chore(deps): do not upgrade indirect Go deps
  Makefile
Labels: OCA Verified

#192 refactor: run policy engine using macaron entrypoint
  README.md
  pyproject.toml
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  scripts/release_scripts/run_macaron.sh
  src/macaron/__main__.py
  src/macaron/config/global_config.py
  src/macaron/policy_engine/__main__.py
  src/macaron/policy_engine/policy_engine.py
  src/macaron/policy_engine/policy_registry.py
  src/macaron/slsa_analyzer/analyzer.py
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_datalog.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_yaml_invalid.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_yaml_poc.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_yml_invalid.json
  tests/e2e/expected_results/urllib3/urllib3_cue_datalog.json
  tests/policy_engine/resources/policies/slsa_verifier.yaml
  tests/policy_engine/resources/policies/urllib3/urllib3.cue
  tests/policy_engine/resources/policies/urllib3/urllib3.dl
  tests/policy_engine/resources/policies/valid/policytest.cue
  tests/policy_engine/test_main.py
Labels: OCA Verified

#212 chore: update Souffle to version 2.4
  Makefile
  docker/Dockerfile.base
  docker/Dockerfile.final
Labels: OCA Verified

#155 feat: add repo finding via scm metadata in artefact poms
  pyproject.toml
  src/macaron/config/defaults.ini
  src/macaron/config/global_config.py
  src/macaron/dependency_analyzer/dependency_resolver.py
  src/macaron/dependency_analyzer/java_repo_finder.py
  tests/dependency_analyzer/cyclonedx/defaults.ini
  tests/dependency_analyzer/cyclonedx/test_cyclonedx.py
  tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
  tests/dependency_analyzer/java_repo_finder/__init__.py
  tests/dependency_analyzer/java_repo_finder/resources/example_pom.xml
  tests/dependency_analyzer/java_repo_finder/test_java_repo_finder.py
Labels: OCA Verified

#219 chore(deps): update slsa-verifier to v2.3.0
  Makefile
Labels: OCA Verified

#216 fix: restore the runner if an uncaught exception happens in a check (#132)
  src/macaron/slsa_analyzer/registry.py
Labels: OCA Verified

#214 chore: pass GITHUB_TOKEN from environment variable instead of cmd arg (#199)
  README.md
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  scripts/release_scripts/run_macaron.sh
  src/macaron/__main__.py
  src/macaron/config/global_config.py
Labels: OCA Verified

#223 chore: add indent to expected dependency json files
  src/macaron/dependency_analyzer/cyclonedx.py
  src/macaron/output_reporter/reporter.py
  tests/dependency_analyzer/expected_results/apache_maven_with_sbom_provided.json
  tests/dependency_analyzer/expected_results/cyclonedx_FasterXML_jackson-databind.json
  tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
  tests/dependency_analyzer/expected_results/cyclonedx_micronaut-projects_micronaut-core.json
  tests/dependency_analyzer/expected_results/skipdep_micronaut-projects_micronaut-core.json
Labels: OCA Verified

#228 chore: do not add a duplicate dependency to result record
  src/macaron/output_reporter/results.py
  src/macaron/slsa_analyzer/analyzer.py
Labels: OCA Verified

#230 chore: do not convert Iterable object to list in finding urls
  src/macaron/dependency_analyzer/cyclonedx.py
  src/macaron/dependency_analyzer/dependency_resolver.py
Labels: OCA Verified

#221 docs: update Sphinx's API documentation
  docs/README.md
  docs/source/pages/apidoc/macaron.dependency_analyzer.rst
  docs/source/pages/apidoc/macaron.output_reporter.rst
  docs/source/pages/apidoc/macaron.policy_engine.rst
  docs/source/pages/apidoc/macaron.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.build_tool.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.checks.rst
  docs/source/pages/apidoc/macaron.slsa_analyzer.rst
Labels: OCA Verified

#234 ci: add actionlint check and fix errors
  .github/workflows/codeql-analysis.yaml
  .pre-commit-config.yaml
  Makefile
Labels: OCA Verified

#233 chore(flake8): improve the flake8 configuration
  .flake8
Labels: OCA Verified

#236 fix: upgrade requests to 2.31.0 to fix CVE-2023-32681
  pyproject.toml
Labels: OCA Verified

#238 fix: do not overwrite an existing check relationship when a check has no parent in the Registry
  src/macaron/slsa_analyzer/registry.py
Labels: bug, OCA Verified

#240 test: add a Make target for Docker integration tests
  .github/workflows/_build_docker.yaml
  Makefile
Labels: OCA Verified

#242 build: remove login step because macaron-base is public
  .github/workflows/_build_docker.yaml
Labels: OCA Verified

#241 fix: add 'packages: read' permission to release workflow
  .github/workflows/release.yaml
Labels: OCA Verified

#243 build: add a Makefile target for building the Docker image
  .github/workflows/_build_docker.yaml
  .github/workflows/release.yaml
  Makefile
Labels: OCA Verified

#245 fix: create the bin directory for syft
  .github/workflows/release.yaml
Labels: OCA Verified

#246 build: add a Makefile target to push the Docker image
  .github/workflows/release.yaml
  Makefile
Labels: OCA Verified

#244 build: use make setup install commitizen
  .github/workflows/release.yaml
  Makefile
  pyproject.toml
Labels: OCA Verified

#247 ci: add a workflow to rebase staging on main after release
  .github/workflows/_generate-rebase.yaml
  .github/workflows/release.yaml
Labels: OCA Verified

#252 fix: do not skip rootProject in Gradle dependency resolution
  src/macaron/resources/init.gradle
Labels: OCA Verified

#249 ci(deploy): add a workflow to deploy docs to GitHub pages
  .github/workflows/_deploy-github-pages.yaml
  .github/workflows/release.yaml
Labels: OCA Verified

#232 docs: add tutorials for running macaron
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/dependencies.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/junit5.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/junit5.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-core.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-core.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-validation.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-validation.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactive-streams.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactive-streams.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactor-core.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactor-core.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_sbom/dependencies.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_sbom/micronaut-core.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_sbom/micronaut-core.json
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_sbom/sbom.json
  docs/source/index.rst
  docs/source/pages/apidoc/index.rst
  docs/source/pages/cli_options.rst
  docs/source/pages/installation.rst
  docs/source/pages/output_files.rst
  docs/source/pages/using.rst
Labels: documentation, OCA Verified

#259 ci(release): add a step to determine release info
  .github/workflows/release.yaml
Labels: OCA Verified

#217 feat: add additional repo finding via parent POMs
  src/macaron/config/defaults.ini
  src/macaron/dependency_analyzer/dependency_resolver.py
  src/macaron/dependency_analyzer/java_repo_finder.py
  tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
  tests/dependency_analyzer/java_repo_finder/resources/example_pom_no_scm.xml
  tests/dependency_analyzer/java_repo_finder/test_java_repo_finder.py
Labels: OCA Verified

#262 feat: add command-line flag for version
  src/macaron/__main__.py
  tests/test_main.py
Labels: OCA Verified

#261 ci(release): add release version to SBOM and provenance names
  .github/workflows/release.yaml
Labels: OCA Verified
