Repository oracle/macaron, pull requests merged in 2023-06, with the labels that each got.

#265 feat(release): generate SLSA provenance for the Docker image
  .github/workflows/release.yaml
Labels: OCA Verified

#268 chore(deps): fix actions/checkout versions in comments
  .github/workflows/_build_docker.yaml
  .github/workflows/build_base_image.yaml
Labels: OCA Verified

#273 chore: disable release Slack notification for now
  .github/workflows/release.yaml
Labels: OCA Verified

#274 chore: enable push event in release workflow
  .github/workflows/release.yaml
Labels: OCA Verified

#270 chore: remove running the policy engine when --show-prelude is provided
  src/macaron/__main__.py
  src/macaron/policy_engine/policy_engine.py
Labels: bug, OCA Verified

#277 fix(release): disable SLSA provenance for now
  .github/workflows/release.yaml
Labels: OCA Verified

#269 docs: update CLI Usage page in the Sphinx documentation
  docs/source/index.rst
  docs/source/pages/cli_options.rst
  docs/source/pages/cli_usage/action_analyze.rst
  docs/source/pages/cli_usage/action_dump_defaults.rst
  docs/source/pages/cli_usage/action_verify-policy.rst
  docs/source/pages/cli_usage/index.rst
  docs/source/pages/installation.rst
  docs/source/pages/using.rst
Labels: documentation, OCA Verified

#276 chore: update README in the docs directory
  docs/README.md
Labels: OCA Verified

#280 chore: add copyright header to action command RST files
  docs/source/pages/cli_usage/action_analyze.rst
  docs/source/pages/cli_usage/action_dump_defaults.rst
  docs/source/pages/cli_usage/action_verify-policy.rst
Labels: OCA Verified

#279 docs: adjust README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: OCA Verified

#282 build(docs): check changes to rst files in Makefile
  Makefile
Labels: OCA Verified

#281 docs: update the Output Files Guide page in the Sphinx documentation
  docs/source/pages/output_files.rst
  docs/source/pages/using.rst
Labels: OCA Verified

#284 docs: add policy related docs and improve examples
  docs/source/_static/examples/micronaut-projects/micronaut-core/policies/micronaut-core.cue
  docs/source/_static/examples/oracle-quickstart/oci-micronaut/policies/oci-micronaut.dl
  docs/source/_static/images/macaron_infrastructure.png
  docs/source/index.rst
  docs/source/pages/using.rst
Labels: OCA Verified

#289 docs: adjust the copyright in documentations
  docs/source/conf.py
Labels: OCA Verified

#290 chore(deps-dev): update Syft from 0.82.0 to 0.83.0
  .github/workflows/release.yaml
Labels: OCA Verified

#299 fix: fixes the result summary for UNKNOWN check results
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/checks/check_result.py
  tests/e2e/expected_results/micronaut-core/micronaut-core.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_datalog.json
  tests/e2e/expected_results/slsa-verifier/slsa-verifier_yaml_invalid.json
Labels: OCA Verified

#310 chore: update documentation
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  SECURITY.md
  build_spec.yaml
Labels: OCA Verified

#307 chore: change repository links to oracle/macaron
  .github/workflows/_build_docker.yaml
  .github/workflows/build_base_image.yaml
  .github/workflows/release.yaml
  README.md
  docker/Dockerfile.final
  docs/README.md
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/junit5.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-core.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/micronaut-validation.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactive-streams.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_repo_path/reactor-core.html
  docs/source/_static/examples/micronaut-projects/micronaut-core/analyze_with_sbom/micronaut-core.html
  docs/source/pages/installation.rst
  docs/source/pages/using.rst
  go.mod
  golang/cmd/actionparser/actionparser.go
  golang/cmd/bashparser/bashparser.go
  scripts/dev_scripts/integration_tests.sh
  scripts/release_scripts/run_macaron.sh
  src/macaron/code_analyzer/call_graph.py
  src/macaron/output_reporter/results.py
  src/macaron/output_reporter/templates/base_template.html
  src/macaron/slsa_analyzer/analyzer.py
Labels: OCA Verified

#312 docs: fix issues in README.md
  README.md
Labels: OCA Verified

#315 fix: fix CycloneDx Gradle automatic dependency resolver bug
  Makefile
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  src/macaron/resources/.gitignore
  tests/dependency_analyzer/expected_results/cyclonedx_timyarkov_multibuild_test.json
  tests/e2e/expected_results/multibuild_test/multibuild_test.json
Labels: OCA Verified

#318 ci: update expected results for actionparser
  .pre-commit-config.yaml
  go.mod
  go.sum
  tests/parsers/actionparser/__snapshots__/test_actionparser.ambr
  tests/parsers/actionparser/resources/expected_results/codeql-analysis.json
  tests/parsers/actionparser/resources/expected_results/maven.json
  tests/parsers/actionparser/resources/expected_results/release.json
  tests/parsers/actionparser/test_actionparser.py
Labels: OCA Verified

#179 feat: multi build tool detection
  scripts/dev_scripts/integration_tests.sh
  src/macaron/dependency_analyzer/cyclonedx_mvn.py
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/build_tool/base_build_tool.py
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_script_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  src/macaron/slsa_analyzer/specs/build_spec.py
  tests/dependency_analyzer/expected_results/cyclonedx_timyarkov_multibuild_test.json
  tests/e2e/expected_results/multibuild_test/multibuild_test.json
  tests/slsa_analyzer/checks/test_build_as_code_check.py
  tests/slsa_analyzer/checks/test_build_script_check.py
  tests/slsa_analyzer/checks/test_build_service_check.py
  tests/slsa_analyzer/checks/test_vcs_check.py
Labels: OCA Verified

#316 feat: add support for cloning GitLab repositories
  scripts/dev_scripts/integration_tests.sh
  scripts/release_scripts/run_macaron.sh
  src/macaron/__main__.py
  src/macaron/config/defaults.ini
  src/macaron/errors.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_service/__init__.py
  src/macaron/slsa_analyzer/git_service/base_git_service.py
  src/macaron/slsa_analyzer/git_service/bitbucket.py
  src/macaron/slsa_analyzer/git_service/github.py
  src/macaron/slsa_analyzer/git_service/gitlab.py
  src/macaron/slsa_analyzer/git_url.py
  tests/e2e/expected_results/tinyMediaManager/tinyMediaManager.json
  tests/slsa_analyzer/git_service/test_github.py
  tests/slsa_analyzer/git_service/test_gitlab.py
  tests/slsa_analyzer/test_git_url.py
Labels: OCA Verified

#331 chore(deps-dev): update Syft from 0.83.0 to 0.84.0
  .github/workflows/release.yaml
Labels: OCA Verified

#329 chore: catch AttributeError exception while processing SBOM
  src/macaron/dependency_analyzer/cyclonedx.py
Labels: OCA Verified

#330 chore: fix broken SBOM example link in Sphinx documentation
  docs/source/pages/using.rst
Labels: OCA Verified
