Repository oracle/macaron, pull requests merged in 2023-11, with the labels that each got.

#512 fix: resolve podman compatibility issues
  scripts/release_scripts/run_macaron.sh
Labels: OCA Verified

#540 test: pin the Docker images used in tests
  tests/slsa_analyzer/build_tool/mock_repos/docker_repos/nested_dockerfile/project/Dockerfile
  tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_dockerfile/Dockerfile
  tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_dockerfile_wildcard/Dockerfile.final
  tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_wildcard_dockerfile/final.Dockerfile
Labels: OCA Verified

#513 refactor: refactor interface of base check
  src/macaron/output_reporter/results.py
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/checks/base_check.py
  src/macaron/slsa_analyzer/checks/build_as_code_check.py
  src/macaron/slsa_analyzer/checks/build_script_check.py
  src/macaron/slsa_analyzer/checks/build_service_check.py
  src/macaron/slsa_analyzer/checks/check_result.py
  src/macaron/slsa_analyzer/checks/infer_artifact_pipeline_check.py
  src/macaron/slsa_analyzer/checks/provenance_available_check.py
  src/macaron/slsa_analyzer/checks/provenance_l3_check.py
  src/macaron/slsa_analyzer/checks/provenance_l3_content_check.py
  src/macaron/slsa_analyzer/checks/provenance_witness_l1_check.py
  src/macaron/slsa_analyzer/checks/trusted_builder_l3_check.py
  src/macaron/slsa_analyzer/checks/vcs_check.py
  src/macaron/slsa_analyzer/database_store.py
  src/macaron/slsa_analyzer/registry.py
  src/macaron/slsa_analyzer/runner.py
  src/macaron/slsa_analyzer/slsa_req.py
  tests/slsa_analyzer/checks/base_check/test_base_check.py
  tests/slsa_analyzer/checks/test_build_as_code_check.py
  tests/slsa_analyzer/checks/test_build_script_check.py
  tests/slsa_analyzer/checks/test_build_service_check.py
  tests/slsa_analyzer/checks/test_infer_artifact_pipeline.py
  tests/slsa_analyzer/checks/test_provenance_available_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_check.py
  tests/slsa_analyzer/checks/test_provenance_l3_content_check.py
  tests/slsa_analyzer/checks/test_registry.py
  tests/slsa_analyzer/checks/test_trusted_builder_l3_check.py
  tests/slsa_analyzer/checks/test_vcs_check.py
  tests/slsa_analyzer/runner/test_runner.py
  tests/slsa_analyzer/test_analyze_context.py
  tests/slsa_analyzer/test_slsa_requirements.py
Labels: OCA Verified

#539 docs: add the new build tools and adjust supported technologies
  README.md
  docs/source/pages/supported_technologies/index.rst
Labels: OCA Verified

#529 chore: display the repository URL status of dependencies in html report instead of the analysis status
  src/macaron/output_reporter/jinja2_extensions.py
  src/macaron/output_reporter/results.py
  src/macaron/output_reporter/templates/macaron.html
Labels: OCA Verified

#389 perf: use partial clone to reduce clone time
  docs/source/pages/developers_guide/apidoc/macaron.rst
  src/macaron/environment_variables.py
  src/macaron/slsa_analyzer/git_url.py
  tests/test_environment_variables.py
Labels: OCA Verified, git_operations

#536 chore: use --force for running git checkout to prevent issues like #530
  docs/source/pages/using.rst
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/git_url.py
Labels: bug, OCA Verified, git_operations

#552 test: replace some micronaut-core tests with micronaut-test to reduce integration test time
  scripts/dev_scripts/integration_tests.sh
  tests/dependency_analyzer/configurations/micronaut_test_config.yaml
  tests/dependency_analyzer/expected_results/cyclonedx_micronaut-projects_micronaut-core.json
  tests/dependency_analyzer/expected_results/cyclonedx_micronaut-projects_micronaut-test.json
  tests/dependency_analyzer/expected_results/skipdep_micronaut-projects_micronaut-test.json
  tests/e2e/configurations/micronaut_test_config.yaml
  tests/e2e/expected_results/micronaut-test/caffeine.json
  tests/e2e/expected_results/micronaut-test/dependencies.json
  tests/e2e/expected_results/micronaut-test/micronaut-test.json
  tests/e2e/expected_results/micronaut-test/slf4j.json
Labels: OCA Verified

#544 test: add update option to integration script
  Makefile
  scripts/dev_scripts/integration_tests.sh
Labels: OCA Verified

#556 docs: treat Sphinx warnings as erros
  docs/Makefile
  pyproject.toml
Labels: OCA Verified

#551 feat: find SLSA provenance v0.2 published on npm registry
  Makefile
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.package_registry.rst
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.provenance.rst
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.provenance.slsa.rst
  docs/source/pages/supported_technologies/index.rst
  docs/source/pages/supported_technologies/npm_registry.rst
  scripts/dev_scripts/integration_tests.sh
  src/macaron/config/defaults.ini
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/checks/provenance_available_check.py
  src/macaron/slsa_analyzer/package_registry/__init__.py
  src/macaron/slsa_analyzer/package_registry/maven_central_registry.py
  src/macaron/slsa_analyzer/package_registry/npm_registry.py
  src/macaron/slsa_analyzer/provenance/slsa/__init__.py
  tests/conftest.py
  tests/e2e/expected_results/purl/npm/sigstore/mock/mock.json
  tests/slsa_analyzer/checks/test_provenance_available_check.py
  tests/slsa_analyzer/package_registry/test_npm_registry.py
  tests/slsa_analyzer/provenance/resources/valid_provenances/sigstore-mock.payload.json
  tests/slsa_analyzer/test_analyzer.py
Labels: OCA Verified

#555 chore: resolve doctest issues
  pyproject.toml
  src/macaron/config/defaults.py
  src/macaron/output_reporter/jinja2_extensions.py
  src/macaron/output_reporter/results.py
  src/macaron/policy_engine/souffle_code_generator.py
  src/macaron/slsa_analyzer/git_service/api_client.py
  src/macaron/slsa_analyzer/git_url.py
  src/macaron/slsa_analyzer/registry.py
  src/macaron/util.py
Labels: OCA Verified

#524 chore: improve cyclonedx-mvn bom file check to include files with cus…
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  src/macaron/dependency_analyzer/cyclonedx.py
  src/macaron/dependency_analyzer/cyclonedx_mvn.py
  tests/dependency_analyzer/configurations/maven_config.yaml
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/multiple_named_sboms/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/multiple_named_sboms/target/custom_bom_2.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom_with_children/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom_with_children/target/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom_with_multiple_children/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom_with_multiple_children/target/target/custom_bom.json
  tests/dependency_analyzer/cyclonedx/resources/sbom_name_tests/single_named_sbom_with_multiple_children/target/target/custom_bom_2.json
  tests/dependency_analyzer/cyclonedx/test_cyclonedx.py
  tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
  tests/e2e/configurations/maven_config.yaml
  tests/e2e/configurations/maven_digest_no_branch.yaml
  tests/e2e/configurations/maven_local_path.yaml
  tests/e2e/expected_results/maven/maven.json
  tests/e2e/expected_results/purl/com_google_guava/guava/guava.json
  tests/e2e/expected_results/purl/maven/maven.json
Labels: OCA Verified
