Repository oracle/macaron, pull requests merged in 2024-08, with the labels that each got.

#812 chore(deps-dev): add test-docker dependencies to pyproject.toml
  Makefile
  pyproject.toml
Labels: OCA Verified, tests

#815 chore: add a new tag for tutorial integration tests
  CONTRIBUTING.md
  tests/integration/README.md
  tests/integration/cases/apache_maven_cyclonedx_sbom_tutorial/test.yaml
  tests/integration/cases/apache_maven_sbom_no_repo_tutorial/test.yaml
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/test.yaml
  tests/integration/cases/example_maven_app_automatic_dep_resolution_tutorial/test.yaml
Labels: documentation, OCA Verified, tests

#806 docs: add tutorial for npm provenance extraction and verification
  docs/source/_static/images/tutorial_semver_7.6.2_report.png
  docs/source/pages/tutorials/commit_finder.rst
  docs/source/pages/tutorials/detect_malicious_java_dep.rst
  docs/source/pages/tutorials/generate_verification_summary_attestation.rst
  docs/source/pages/tutorials/index.rst
  docs/source/pages/tutorials/npm_provenance.rst
  tests/integration/cases/semver/policy.dl
  tests/integration/cases/semver/test.yaml
  tests/integration/cases/tutorial_npm_verify_provenance_semver/policy_7_6_2.dl
  tests/integration/cases/tutorial_npm_verify_provenance_semver/policy_7_6_x.dl
  tests/integration/cases/tutorial_npm_verify_provenance_semver/policy_7_plus.dl
  tests/integration/cases/tutorial_npm_verify_provenance_semver/test.yaml
Labels: OCA Verified

#818 docs: exclude hyphenated attributes in sphinx docs
  docs/source/conf.py
  docs/source/pages/developers_guide/apidoc/macaron.parsers.rst
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.checks.rst
Labels: OCA Verified

#816 docs: add a tutorial for malware detection check
  docs/source/_static/images/tutorial_django_5.0.6_detect_malicious_metadata_check.png
  docs/source/assets/er-diagram.svg
  docs/source/index.rst
  docs/source/pages/supported_technologies/index.rst
  docs/source/pages/supported_technologies/pypi_registry.rst
  docs/source/pages/tutorials/detect_malicious_package.rst
  docs/source/pages/tutorials/exclude_include_checks.rst
  docs/source/pages/tutorials/index.rst
  docs/source/pages/using.rst
  src/macaron/database/table_definitions.py
  src/macaron/policy_engine/prelude/helper_rules.dl
  src/macaron/slsa_analyzer/checks/check_result.py
  src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/configurations.ini
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/policy-all-pypi.dl
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/policy-recursive-deps-confidence.dl
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/policy-recursive-deps.dl
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/test.yaml
  tests/policy_engine/resources/facts/macaron.db.gz
  tests/policy_engine/resources/policies/valid/testpolicy.dl
Labels: OCA Verified

#825 docs: emphasize Python 3.11 requirement for Python dep analysis
  docs/source/pages/tutorials/detect_malicious_package.rst
Labels: OCA Verified

#826 chore: update v0110 third party licenses
  THIRD_PARTY_LICENSES.txt
Labels: OCA Verified

#829 docs: remove SLSA 0.1 from docs and fix tables
  README.md
  docs/source/_static/style.css
  docs/source/index.rst
  docs/source/pages/checks/slsa_builds.rst
  docs/source/pages/cli_usage/command_analyze.rst
Labels: OCA Verified

#831 chore: remove get group id using gradlew logic
  src/macaron/slsa_analyzer/build_tool/gradle.py
  tests/slsa_analyzer/build_tool/test_gradle.py
Labels: OCA Verified

#842 chore: update third party license file for v0120
  THIRD_PARTY_LICENSES.txt
Labels: OCA Verified
