Repository oracle/macaron, pull requests merged in 2024-07, with the labels that each got.

#783 test: use python instead of python3
  .pre-commit-config.yaml
  docs/README.md
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  tests/integration/README.md
  tests/integration/run.py
Labels: OCA Verified

#780 chore: improve token support in run_macaron.sh
  .gitignore
  scripts/dev_scripts/integration_tests.sh
  scripts/dev_scripts/integration_tests_docker.sh
  scripts/release_scripts/run_macaron.sh
  tests/integration/cases/apache_maven_local_repo/test.yaml
  tests/integration/cases/apache_maven_purl_repo_path/test.yaml
  tests/integration/cases/apache_maven_sbom/test.yaml
  tests/integration/cases/apache_maven_yaml_input_skip_deps/test.yaml
  tests/integration/cases/apache_maven_yaml_input_with_dep_resolution/test.yaml
  tests/integration/cases/behnazh-w_example-maven-app/test.yaml
  tests/integration/cases/invalid_purl/test.yaml
  tests/integration/cases/no_branch_or_commit/test.yaml
  tests/integration/cases/no_github_token/test.yaml
  tests/integration/cases/ossf_scorecard/test.yaml
  tests/integration/cases/run_macaron_sh_early_exit/test.yaml
  tests/integration/cases/run_macaron_sh_with_invalid_docker_pull_env/test.yaml
  tests/integration/cases/slsa-framework_slsa-verifier/test.yaml
  tests/integration/cases/timyarkov_multibuild_test_gradle/test.yaml
  tests/integration/cases/timyarkov_multibuild_test_maven/test.yaml
  tests/integration/cases/urllib3_expectation_dir/test.yaml
  tests/integration/cases/urllib3_expectation_file/test.yaml
  tests/integration/cases/urllib3_invalid_expectation/test.yaml
Labels: OCA Verified

#786 chore: add exclude and include tag options to update command and add logging of each test case to update command
  tests/integration/run.py
Labels: bug, OCA Verified, tests

#750 feat: add a check to analyze malicious Python packages
  pyproject.toml
  src/macaron/config/defaults.ini
  src/macaron/malware_analyzer/README.md
  src/macaron/malware_analyzer/__init__.py
  src/macaron/malware_analyzer/checks/__init__.py
  src/macaron/malware_analyzer/checks/detect_malicious_metadata_check.py
  src/macaron/malware_analyzer/datetime_parser.py
  src/macaron/malware_analyzer/pypi_heuristics/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/base_analyzer.py
  src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/closer_release_join_date.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/empty_project_link.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/high_release_frequency.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/one_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unchanged_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unreachable_project_links.py
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/package_registry/__init__.py
  src/macaron/slsa_analyzer/package_registry/pypi_registry.py
  tests/conftest.py
  tests/malware_analyzer/pypi/test_closer_release_join_date.py
  tests/malware_analyzer/pypi/test_empty_project_link_analyzer.py
  tests/malware_analyzer/pypi/test_high_release_frequency.py
  tests/malware_analyzer/pypi/test_one_release_analyzer.py
  tests/malware_analyzer/pypi/test_suspicious_setup.py
  tests/malware_analyzer/pypi/test_unchanged_release.py
  tests/malware_analyzer/pypi/test_unreachable_project_links_analyzer.py
Labels: OCA Verified

#790 chore: restrict malware check to python projects; apply general fixes…
  src/macaron/malware_analyzer/README.md
  src/macaron/malware_analyzer/__init__.py
  src/macaron/malware_analyzer/checks/__init__.py
  src/macaron/malware_analyzer/checks/detect_malicious_metadata_check.py
  src/macaron/malware_analyzer/datetime_parser.py
  src/macaron/malware_analyzer/pypi_heuristics/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/closer_release_join_date.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/empty_project_link.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/high_release_frequency.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/one_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unchanged_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unreachable_project_links.py
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/__init__.py
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
  src/macaron/slsa_analyzer/package_registry/pypi_registry.py
  src/macaron/util.py
  tests/malware_analyzer/pypi/test_closer_release_join_date.py
  tests/malware_analyzer/pypi/test_empty_project_link_analyzer.py
  tests/malware_analyzer/pypi/test_high_release_frequency.py
  tests/malware_analyzer/pypi/test_one_release_analyzer.py
  tests/malware_analyzer/pypi/test_suspicious_setup.py
  tests/malware_analyzer/pypi/test_unchanged_release.py
  tests/malware_analyzer/pypi/test_unreachable_project_links_analyzer.py
Labels: OCA Verified

#795 chore: update django dependency policy to ignore minor version changes
  tests/policy_engine/resources/policies/django/test_dependencies.dl
Labels: OCA Verified

#799 chore(mypy): remove redundant mypy_path configuration for type checking
  pyproject.toml
Labels: OCA Verified

#796 fix: use artifact filenames as keys for verifying jfrog assets in provenance_witness_l1_check
  src/macaron/slsa_analyzer/checks/provenance_witness_l1_check.py
  src/macaron/slsa_analyzer/provenance/witness/__init__.py
  tests/integration/cases/behnazh-w_example-maven-app/policy.dl
  tests/integration/cases/behnazh-w_example-maven-app/policy_report.json
  tests/integration/cases/behnazh-w_example-maven-app/vsa_payload.json
  tests/slsa_analyzer/checks/test_provenance_witness_l1_check.py
Labels: bug, OCA Verified

#747 feat: verify npm SLSA provenance against signed npm provenance
  docs/source/index.rst
  docs/source/pages/checks/slsa_builds.rst
  src/macaron/config/defaults.ini
  src/macaron/repo_finder/provenance_finder.py
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/checks/provenance_verified_check.py
  src/macaron/slsa_analyzer/package_registry/npm_registry.py
  tests/integration/cases/semver/policy.dl
  tests/integration/cases/sigstore_mock/policy.dl
  tests/integration/cases/sigstore_sget/policy.dl
Labels: OCA Verified

#797 chore: improve the malicious metadata check
  docs/source/pages/developers_guide/apidoc/macaron.database.rst
  docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.pypi_heuristics.metadata.rst
  docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.pypi_heuristics.rst
  docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.pypi_heuristics.sourcecode.rst
  docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.rst
  docs/source/pages/developers_guide/apidoc/macaron.rst
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.checks.rst
  docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.package_registry.rst
  pyproject.toml
  src/macaron/code_analyzer/call_graph.py
  src/macaron/config/defaults.ini
  src/macaron/database/db_custom_types.py
  src/macaron/database/table_definitions.py
  src/macaron/malware_analyzer/checks/__init__.py
  src/macaron/malware_analyzer/datetime_parser.py
  src/macaron/malware_analyzer/pypi_heuristics/base_analyzer.py
  src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/closer_release_join_date.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/empty_project_link.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/high_release_frequency.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/one_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unchanged_release.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/unreachable_project_links.py
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
  src/macaron/policy_engine/souffle_code_generator.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
  src/macaron/slsa_analyzer/package_registry/pypi_registry.py
  src/macaron/slsa_analyzer/specs/package_registry_spec.py
  tests/conftest.py
  tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/policy.dl
  tests/malware_analyzer/pypi/conftest.py
  tests/malware_analyzer/pypi/test_closer_release_join_date.py
  tests/malware_analyzer/pypi/test_empty_project_link_analyzer.py
  tests/malware_analyzer/pypi/test_high_release_frequency.py
  tests/malware_analyzer/pypi/test_one_release_analyzer.py
  tests/malware_analyzer/pypi/test_suspicious_setup.py
  tests/malware_analyzer/pypi/test_unchanged_release.py
  tests/malware_analyzer/pypi/test_unreachable_project_links_analyzer.py
  tests/slsa_analyzer/checks/resources/pypi_files/zlibxjson-8.2.source
  tests/slsa_analyzer/checks/resources/pypi_files/zlibxjson.html
  tests/slsa_analyzer/checks/resources/pypi_files/zlibxjson_package.json
  tests/slsa_analyzer/checks/resources/pypi_files/zlibxjson_user.html
  tests/slsa_analyzer/checks/test_detect_malicious_metadata_check.py
Labels: OCA Verified

#802 fix: accept provenances that are not inferred in the provenance checks
  src/macaron/slsa_analyzer/checks/provenance_available_check.py
  src/macaron/slsa_analyzer/checks/provenance_verified_check.py
Labels: OCA Verified

#809 docs: update Installation Guide with Docker Desktop instructions
  docs/source/pages/installation.rst
Labels: OCA Verified

#810 chore: add CLOSER_RELEASE_JOIN_DATE heuristic as a dependency of SUSPICIOUS_SETUP
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
Labels: OCA Verified
