Repository oracle/macaron, pull requests merged in 2024-03, with the labels that each got.

#654 chore: add provenance as an input CLI option
  docs/source/pages/cli_usage/command_analyze.rst
  scripts/dev_scripts/integration_tests.sh
  src/macaron/__main__.py
  src/macaron/slsa_analyzer/analyze_context.py
  src/macaron/slsa_analyzer/analyzer.py
Labels: OCA Verified, slsa-provenance

#639 feat: discover slsa v1 provenances for npm packages
  src/macaron/slsa_analyzer/package_registry/npm_registry.py
  src/macaron/slsa_analyzer/provenance/intoto/__init__.py
  src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
  src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
  tests/slsa_analyzer/package_registry/test_npm_registry.py
  tests/slsa_analyzer/provenance/intoto/v1/__init__.py
  tests/slsa_analyzer/provenance/intoto/v1/test_validate.py
Labels: OCA Verified, slsa-provenance

#641 chore: use priority ordering in java repo finder
  src/macaron/config/defaults.ini
  src/macaron/repo_finder/repo_finder_java.py
  src/macaron/repo_finder/repo_validator.py
  tests/repo_finder/test_repo_finder.py
Labels: OCA Verified

#658 docs: improve the signing and PR contribution instructions
  CONTRIBUTING.md
Labels: OCA Verified

#660 fix: preserve the order of elements of the list extract from defaults.ini
  src/macaron/config/defaults.py
  src/macaron/repo_finder/repo_finder_java.py
  src/macaron/slsa_analyzer/registry.py
  tests/config/test_defaults.py
Labels: bug, OCA Verified

#667 docs: add exclude include check feature tutorial
  docs/source/_static/images/exclude_provenance_withness_level_one.png
  docs/source/pages/developers_guide/index.rst
  docs/source/pages/tutorials/detect_malicious_java_dep.rst
  docs/source/pages/tutorials/exclude_include_checks.rst
  docs/source/pages/tutorials/index.rst
Labels: documentation, OCA Verified

#674 chore(deps): update slsa-verifier to v2.4.1
  Makefile
Labels: OCA Verified

#676 chore: exclude provenance check in micronaut-core temporarily
  scripts/dev_scripts/integration_tests.sh
  tests/e2e/defaults/micronaut-core.ini
  tests/e2e/expected_results/micronaut-core/micronaut-core.json
  tests/e2e/expected_results/purl/maven/micronaut-core/micronaut-core.json
Labels: OCA Verified

#653 feat: use provenance to find commits for supported PURL types.
  scripts/dev_scripts/integration_tests.sh
  src/macaron/__main__.py
  src/macaron/errors.py
  src/macaron/json_tools.py
  src/macaron/repo_finder/provenance_extractor.py
  src/macaron/repo_finder/provenance_finder.py
  src/macaron/repo_finder/repo_finder.py
  src/macaron/slsa_analyzer/analyzer.py
  src/macaron/slsa_analyzer/package_registry/npm_registry.py
  src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
  src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
  src/macaron/slsa_analyzer/provenance/witness/__init__.py
  tests/e2e/defaults/disable_repo_finder.ini
  tests/e2e/expected_results/purl/npm/semver/semver.json
  tests/repo_finder/test_provenance_extractor.py
  tests/repo_finder/test_repo_finder.py
  tests/slsa_analyzer/test_analyzer.py
Labels: OCA Verified

#675 chore: use dunder function __str__ when requiring a string serialization of a PackageURL object
  src/macaron/repo_finder/repo_finder.py
  src/macaron/slsa_analyzer/analyzer.py
Labels: OCA Verified
