Repository oracle/macaron, pull requests merged in 2025-08, with the labels that each got.

#1137 chore: update third party license for release v0.17.0
  THIRD_PARTY_LICENSES.txt
Labels: release

#1138 fix: catch defusedxml security errors
  src/macaron/parsers/pomparser.py
  tests/parsers/pomparser/__init__.py
  tests/parsers/pomparser/resources/forbidden_entity.xml
  tests/parsers/pomparser/resources/invalid.xml
  tests/parsers/pomparser/resources/valid.xml
  tests/parsers/pomparser/test_pomparser.py
Labels: bug, OCA Verified

#1144 chore: fix heuristic dependency handling temporarily
  src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
Labels: OCA Verified

#1089 feat(heuristics): add SimilarProjectAnalyzer to detect structural similarity across packages from same maintainer
  src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
  src/macaron/malware_analyzer/pypi_heuristics/metadata/similar_projects.py
  src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
  src/macaron/slsa_analyzer/package_registry/pypi_registry.py
  tests/malware_analyzer/pypi/test_similar_projects.py
Labels: OCA Verified

#1146 chore: change rules for fake email analyzer to reduce FPs
  src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
Labels: OCA Verified

#1152 chore: fix a bug in SimilarProjectAnalyzer
  src/macaron/malware_analyzer/pypi_heuristics/metadata/similar_projects.py
Labels: OCA Verified

#1155 chore(deps): update Souffle in base image to version 2.5
  .github/workflows/build_base_image.yaml
  docker/Dockerfile.base
Labels: OCA Verified

#1136 test: resolve bugs in sourcecode analyzer to allow unit tests to run offline
  src/macaron/malware_analyzer/pypi_heuristics/sourcecode/pypi_sourcecode_analyzer.py
  tests/malware_analyzer/pypi/test_pypi_sourcecode_analyzer.py
Labels: OCA Verified

#1154 test: refactor fake email heuristic to be more optimistic and allow offline tests
  src/macaron/malware_analyzer/pypi_heuristics/metadata/fake_email.py
  tests/integration/cases/email_checking_pypi_malware_analyzer/check_emails.sh
  tests/integration/cases/email_checking_pypi_malware_analyzer/policy.dl
  tests/integration/cases/email_checking_pypi_malware_analyzer/test.yaml
  tests/malware_analyzer/pypi/test_fake_email.py
Labels: OCA Verified

#1157 chore(deps): update the base Docker image
  docker/Dockerfile.base
  docker/Dockerfile.final
Labels: OCA Verified
